version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  openjdk-install: cloudesire/openjdk-install@1.2.3

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      
